# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  # vagrant box add ubuntu1404 https://github.com/kraksoft/vagrant-box-ubuntu/releases/download/14.04/ubuntu-14.04-amd64.box
  config.vm.box = "ubuntu1404"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true

    # Customize the amount of memory on the VM:
    vb.memory = "1024"
  end
  # config.vm.provision "shell", inline: <<-INSTALL_DESKTOP
  #   sudo apt-get update && sudo apt-get upgrade -y
  #   sudo install ubuntu-desktop lightdm xorg -y
  #   sudo apt-get install xorg gnome-core gnome-system-tools gnome-app-install -y
  # INSTALL_DESKTOP
end
